{% set name = "testpackageignore" %}

package:
  name: {{ name|lower }}
  version: {{ environ.get('PKG_VERSION', '') }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python


