{% set name = "testpackageignore" %}

package:
  name: {{ name|lower }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../

build:
  noarch: python
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python



